name: Security Vulnerability
description: Report a security vulnerability (for non-critical issues only)
title: "[Security]: "
labels: ["security", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **For critical security vulnerabilities, please email security@pegasusheavyindustries.com instead of creating a public issue.**

        This template is for non-critical security issues that can be discussed publicly.

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Describe the security issue
      placeholder: The issue allows...
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this vulnerability?
      options:
        - Low - Minor issue with limited impact
        - Medium - Potential for harm but requires specific conditions
        - High - Significant risk (consider private disclosure)
        - Critical - STOP! Email security@pegasusheavyindustries.com instead
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can this vulnerability be exploited?
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: What is the potential impact of this vulnerability?
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Do you have any suggestions for fixing this?

  - type: checkboxes
    id: disclosure
    attributes:
      label: Responsible Disclosure
      options:
        - label: I understand this issue will be publicly visible
          required: true
        - label: I have verified this is not a critical vulnerability
          required: true
